### PR TITLE
#3941 return decoded hash in getHash()

### PR DESCRIPTION
**Pull request by bobmop**
...to compare correctly to cached fragment in navigate()

### CODE REVIEW

**Comment by akre54** [comment]
@braddunbar ?

**Comment by braddunbar** [comment]
This seems fine to me. I'd say it could even be moved up into `getFragment` since `getPath` calls `decodeFragment` too.

**Comment by bobmop** [comment]
The methods `getPath`and `getHash` are also called separately. I can't figure out the influence...

**Comment by megawac** [comment]
I'm fine with this but it may be a minor breaking change. I'd consider it a bug fix personally though

**Comment by barceyken** [comment]
We added this to our project too :+1:

**Comment by hbomb9000** [comment]
This seems to break browsers 'back' navigation button. However, it does fix the above stated problem.

**Comment by jashkenas** [comment]
> This seems to break browsers 'back' navigation button. However, it does fix the above stated problem.

Uh.

**Comment by platinumazure** [comment]
It'd be great to have normalized hash decoding behavior, but the bit about breaking a browser's "back" button is highly concerning. Does anyone know why that happens? Is it fixable, or is this the wrong direction?

**Comment by Daniel-Alonso-Exabeam** [comment]
This will not work if `match[1]` contains a "%" character that is not used in an encoded character sequence, because the native `decodeURI` function will throw an error. This can happen in two cases:
1. If the encoded fragment passed into `Backbone.history.navigate` contains a "%25". 
2. In Firefox, `this.location.href` returns the url in an encoded format, but "%" characters are not encoded for some reason (there are no "%25").

**Comment by jgonggrijp** [comment]
Rejecting this as it is a breaking change *and* it seems to cause worse problems than it aims to solve.

**Pull request closed without merging**
