### PR TITLE
Fixed updating URL with uri-decoded value

### LINKED ISSUE #4025: Router.navigate generated location.hash regression in 1.2
This change 5821bc03a31b06be3bb69d6344a2acb62024e231 decodes the fragment, and the decoded value goes into `location.hash`, which makes URL effectively malformed.

Quick test to explain the problem:
```javascript
Backbone.history.navigate('search/has%20space');
strictEqual(location.hash, '#search/has%20space');
```

Results:
before 5821bc03a31b06be3bb69d6344a2acb62024e231:
`#search/has%20space`
after:
`#search/has space`

### PR DESCRIPTION
**Pull request by Flamefork**
Fixes #4025

### CODE REVIEW

**Comment by mseeley** [comment]
Ping maintainers. We'd super appreciate some feedback on the fix. Thanks!

**Comment by jridgewell** [comment]
LGTM. @paulfalgout Is there a reason you 👍?

**Comment by paulfalgout** [comment]
No specific reason.  I just happened to run into this bug recently while showing someone something about routes just messing around in the console.  Came to research it and it was the top issue.  Kind of a random chance occurrence. Have not run into it in production.

**Comment by gwynjudd** [comment]
Maybe also fixes #4085. I can't see #4085 any longer having updated to 1.4.0

**Pull request merged**
