### PR TITLE
Remove the micro-opt of caching array length

### PR DESCRIPTION
**Pull request by akre54**
[It's not actually effective](http://mrale.ph/blog/2014/12/24/array-length-caching.html) and it makes the code uglier. 

JSPerf is down at the moment but I seem to remember the benefits in older browsers not even being that great. @jdalton, what say you?

### CODE REVIEW

**Comment by megawac** [comment]
The only case I can see this making a difference is a custom collection which creates a custom object to dynamically compute the `length`. Shitty example

```
function createCollection(items) {
   var result = {};
   var size = items.size;
   items.forEach((item, index) => result[index] = item + 5);
   result.length= {
     valueOf() {
         return size;
     }
   }
}
```

**Comment by jdalton** [comment]
Modern engines will handle the `length` hoisting, this is optimized in IE in Windows 10 preview too. 
Caching a length is handy when you don't want array mutations to affect the iteration count.

**Comment by akre54** [comment]
I think in each of these cases you really shouldn't be mutating the array objects in the first place, right?

**Comment by jdalton** [comment]
> I think in each of these cases you really shouldn't be mutating the array objects in the first place, right?

Nothing appears to be able to access the arrays to mutate them while it's iterating so it should be ok.

**Comment by jashkenas** [comment]
I'm sure that this has gone back-and-forth several times before already ... but whatever ;)

**Comment by akre54** [comment]
@jdalton is this worth [changing in CoffeeScript](http://coffeescript.org/#try:eat%20food%20for%20food%20in%20foods) too?

**Comment by megawac** [comment]
I wouldn't change it there it could break things if the user changes length
i n the loop

**Comment by akre54** [comment]
You probably shouldn't regardless. But fair 'nuff.

**Comment by jashkenas** [comment]
It ain't worth changing in CoffeeScript — there it's a nice micro-optimization that you get for free. The programmer never has to deal with or worry about it.

**Pull request merged**
