### PR TITLE
Use `some`, `includes`, `map` in tests instead of `any`, `include`, `pluck`.

### PR DESCRIPTION
**Pull request by jdalton**
Adjusts tests to follow up #3676.

### CODE REVIEW

**Comment by megawac** [comment]
I'm not sure if we want to do some of this. I would be fine if we did `if _[function] <test>`

**Comment by jdalton** [comment]
>  I would be fine if we did if `_[function] <test>`

I'm not sure what you mean.

**Comment by megawac** [comment]
I mean instead of deleting the `includes`, `max`, `min` tests check if they exist on _ before executing the test

**Comment by jdalton** [comment]
I would use `_.includes` but the version backbone tests doesn't have it. I can fix that though. The `_.max` min tests were adjusted to still test them just without the callback.

**Comment by jdalton** [comment]
Ok updated.

**Pull request merged**
