### PR TITLE
Issue 3996 - Self/Global null fix

### LINKED ISSUE #3996: self (or global) may be null and self.self will throw a exception
`var root = (typeof self == 'object' && self.self === self && self) ||
            (typeof global == 'object' && global.global === global && global);`

so is it `typeof self == 'object' && self && self.self === self` right?

### PR DESCRIPTION
**Pull request by melissawimberly**
This should fix the problem.
Other contributors: @kaidez @wuworkshop @jrmils89 

fixes #3996

### CODE REVIEW

**Comment by akre54** [comment]
Same as #3996 -- is this a real-world issue, or just a hypothetical?

**Comment by siliconforks** [comment]
Wouldn't this be an actual real-world issue if you had a variable `self` with value `null`?  For example, consider the following node.js code:
```node
global.self = null;
const Backbone = require('backbone');
console.log(Backbone.VERSION);
```
If I try to run this with node.js I get:
```
  var root = (typeof self == 'object' && self.self === self && self) ||
                                             ^

TypeError: Cannot read property 'self' of null
```
Note that, in order to fix this, it would also be necessary to fix underscore.js (because it has the same issue).

**Comment by ogonkov** [comment]
It is better to have build tool insert this wrapper

**Comment by jgonggrijp** [comment]
Agreed @ogonkov. Planning to use Rollup for this, as I have done with Underscore.

Also, this is a non-issue, like the linked ticket. Not sure why I put this in the fridge instead of closing it immediately. Perhaps I wanted to reply to the OP, but I guess that isn't necessary.

**Pull request closed without merging**
