### PR TITLE
Minor. Change urlError to urlNeededError and make message more verbose.

### PR DESCRIPTION
**Pull request by sam-at-github**
I'm sure one of the first errors newbs will come across is the urlError Error. It was for me. This minor commit just makes this error a little bit more verbose and easier to understand for newbs like me.

### CODE REVIEW

**Comment by jridgewell** [comment]
Ping: @akre54, what do you think?

**Comment by akre54** [comment]
I don't see how this is any clearer? `A "url" property or function must be specified` vs `No url specified.`

They say the same thing?

**Comment by sam-at-github** [comment]
> I don't see how this is any clearer? A "url" property or function must be specified vs No url specified.

Yeah but that is not an accurate summary of the change.. Newb perspective. It may be the same to you because your experienced with the software. When I first saw this message it sounded a bit cryptic.

**Comment by akre54** [comment]
Sure, I'm happy to merge in something that makes it clearer. But that change is no clearer than the text it replaces.

**Comment by sam-at-github** [comment]
Didn't want to be too specific otherwise you'd lose generality, but It's clearer ...

**Comment by Sendoushi** [comment]
Greetings! 

I've recently found some  amazing information, you  might like and I think it is worth  reading! Just  take a look <http://ltysyndushi.mattbuysgold.com/e4lhif>


Rushing, Alberto Martinez

**Pull request closed without merging**
