### PR TITLE
#4103 check if obj is Model in Collection.get

### PR DESCRIPTION
**Pull request by ksladkov**

### CODE REVIEW

**Comment by akre54** [comment]
Do you have a quickie jsperf to show that the performance hit for this isn't too terrible?

**Comment by ksladkov** [comment]
Yep, it is here: https://jsperf.com/collection-get-ismodel-check

**Comment by akre54** [comment]
I'm getting a script error. Looks like an extra `};` at the end of the file.

**Comment by akre54** [comment]
I'm getting a script error on that jsperf page. Anything obvious?

**Comment by akre54** [comment]
I ran it quickly in the console (which doesn't have the scientific rigor of jsperf), but these are the numbers I got:

```js
console.time(); _.times(200, i => collection1.get(json)); console.timeEnd(); // => 0.249ms
console.time(); _.times(200, i => collection2.get(json)); console.timeEnd(); // => 0.301ms

console.time(); _.times(200, i => collection1.get(model)); console.timeEnd(); // => 0.528ms
console.time(); _.times(200, i => collection2.get(model)); console.timeEnd(); // => 1.31ms
```

**Comment by ksladkov** [comment]
It's surprising for me. I just checked this jsperf on my tablet and got this [screen](https://drive.google.com/file/d/0BwAweRSBiQpWaVRGT0JCXzNDR0U/view?usp=drivesdk)
When I ran this on laptop, I had got 3-4 times more performance, and the ratio was quite similar: collection1.get() was ~5% more performant, but no more.

**Comment by akre54** [comment]
Hm. Ok, getting rid of the duck-typing is reason enough for me. Merging.

**Comment by matthijsgroen** [comment]
I ran into this issue today, when implementing http://jsonapi.org/
glad this is fixed already. Is there a release scheduled ?

**Comment by imp-gino** [comment]
I'm also using JSON API, and this is keeping me from upgrading to 1.3.3 - was a fun troubleshooting experience though! Dunno what's up with 1.4, would be happy with a bugfix release too

**Comment by akre54** [comment]
@braddunbar @jashkenas @jridgewell time to cut a new release :)

**Pull request merged**
