### PR TITLE
Test View

### PR DESCRIPTION
**Pull request by jridgewell**
- Adds some missing `View` tests.
- Returns view from `#delegate` and `#undelegate`

### CODE REVIEW

**Comment by jashkenas** [comment]
Groovy.

**Comment by jashkenas** [comment]
(Just as a fun side-note, for all the SemVer weenies out there, this is a **BREAKING CHANGE**.)

**Comment by jridgewell** [comment]
>  this is a BREAKING CHANGE.

The return value? I'd consider this just a minor release (now returning something), not a major (changing what we were returning).

**Comment by jashkenas** [comment]
That was tongue in cheek. It's a change in behavior. No exceptions. No mercy.

**Pull request merged**
