### PR TITLE
Fixes typo in docs

### PR DESCRIPTION
**Pull request by pra85**
Found a spelling mistake -
`deprectated` > `deprecated`

### CODE REVIEW

**Comment by akre54** [comment]
See also #3939

This file is copied from https://github.com/jeromegn/Backbone.localStorage. Once it gets fixed there we'll pull in the latest.

**Comment by pra85** [comment]
It seems @marksanghoonkim has already opened a PR regarding this issue there https://github.com/jeromegn/Backbone.localStorage/pull/196 

Also didn't notice that #3939 addressed the same issue. 

Then reverting back this PR would be good thing

**Comment by akre54** [comment]
No big deal. We'll leave it for now, and as soon as @marksanghoonkim's PR is merged there we'll pull the other change in too.

**Comment by jridgewell** [comment]
Ha, I should have looked at the file before merging. Whoops.

**Pull request merged**
