### PR TITLE
Add #pluck to collectionMethods

### PR DESCRIPTION
**Pull request by jridgewell**

### CODE REVIEW

**Comment by megawac** [comment]
`Collection#map` is over models not model attributes

**Comment by megawac** [comment]
Sorry I may of been mistaken. Really sorry about that @jridgewell

**Comment by jridgewell** [comment]
Damn, it won't work directly for `#pluck`. But @jdalton opened https://github.com/jashkenas/backbone/pull/3866 that cleans this up.

**Comment by jdalton** [comment]
> it won't work directly for `#pluck`.

Do you have any insight into why it doesn't work?

**Comment by jridgewell** [comment]
Because we would have to pass down a special `(model) => model.get(attr)` function into `_.pluck`, but `_.pluck` internally calls `_.property` coercing the getter into it's source string.

**Pull request closed without merging**
