### PR TITLE
Return removed models from #_removeModels

### PR DESCRIPTION
**Pull request by jridgewell**
Instead of returning a boolean, just return the removed models (or false if nothing is removed).

### CODE REVIEW

**Comment by akre54** [comment]
PhantomJS tests are failing but otherwise nice work!

**Comment by jridgewell** [comment]
Gah, I forgot to add local changes.

**Comment by jridgewell** [comment]
I just can't seem to grok git today... https://github.com/jashkenas/backbone/pull/3639 fixes a syntax error.

**Comment by jridgewell** [comment]
Also, this _is_ a bug fix, highlighted by the [changed tests](https://github.com/jridgewell/backbone/commit/61e765087d955266225dc2eefad26122f1af9975). #3512 incorrectly used `Array#slice` inside `#_removeModels`, which doesn't mutate the `models` variable in `#remove`.

**Comment by jashkenas** [comment]
Ah.

**Pull request merged**
