### PR TITLE
Add out-of-bounds default to Collection#at

### PR DESCRIPTION
**Pull request by tcandens**
With this methods recent change of accepting negative arguments, it bothered me that undefined was being returned half the time. Although this might not be ideal, I feel like it add some consistency.

### CODE REVIEW

**Comment by Florian-R** [comment]
Correct me if i'm wrong, but i think it has already been fixed in gh-3770

**Comment by akre54** [comment]
Yup. Thanks @Florian-R

**Comment by tcandens** [comment]
Looks like gh-3770 was a fix for *adding* models past the end of a collection. This would be simply for accessing collection models with collection.at( index ). This will return the last model when index is beyond length, keeping it consistent with the adding models behavior.

**Comment by akre54** [comment]
My mistake (got thrown off by the "add" in the title...).

I still don't think we should change this. Collections are analogous to Arrays in javascript, and indexing beyond the bounds of an Array returns `undefined`.

It would be overly surprising behavior if we automatically clamped lookups for you (additions are fine, since you're likely just trying to add it to the end of the array already. If you want to get the last value, just use `col.last()`.)

**Pull request closed without merging**
