### PR TITLE
Add alternative help channels to README

### PR DESCRIPTION
**Pull request by akre54**
Github issues are the wrong forum for general discussion and questions (see #3734). Let's direct folks to the right venues.

### CODE REVIEW

**Comment by megawac** [comment]
Yes, definitely!

**Comment by jridgewell** [comment]
:+1:

**Comment by akre54** [comment]
> Should they be added to the index.html as well?

It [already exists](https://github.com/jashkenas/backbone/blob/cb47ea43401d108862b55e0f6b8806993fded1b5/index.html#L559-L566), no?

**Comment by megawac** [comment]
#documentcloud on freenode -> gitter?

**Comment by megawac** [comment]
And add SO?

**Comment by akre54** [comment]
I tend to feel IRC is a better medium than Gitter, but the gitter channel is clearly much better maintained (mostly due to the notification emails, it seems).

**Comment by megawac** [comment]
> I'm torn. I'd rather we favor open content over proprietary silos (i.e. suggest a web search over a StackOverflow)

Well the mailing list is google groups....

> I tend to feel IRC is a better medium than Gitter, but the gitter channel is clearly much better maintained 

I just like not missing messages in the channel. Don't think the irc channel has been active in a while

**Comment by jridgewell** [comment]
StackOverflow, by far.

**Comment by RusAlex** [comment]
IRC is important too. It may be in list next to gitter. They are not
competitors imho.

**Comment by megawac** [comment]
Gitter can be accessed through IRC just FYI

On Tue, Jul 28, 2015 at 4:09 AM, Alexander Pletnev <notifications@github.com

**Comment by jashkenas** [comment]
I'd prioritize IRC over Gitter ... just because, what are the odds of Gitter still being around in the same form in 5 years? But otherwise sounds great.

**Pull request merged**
