### PR TITLE
Remove unused method mapping cases

### PR DESCRIPTION
**Pull request by Shutnik**

### CODE REVIEW

**Comment by megawac** [comment]
I'm = to this, but I kind of like them for consistency

**Comment by akre54** [comment]
Yeah let's leave em in for consistency's sake. I'd argue the alternative would be more confusing.

**Comment by Shutnik** [comment]
@megawac @akre54 This is dead code, there are no exampes and arguments named using magic ball. Why we can't comment that lines for ’consistency‘ and exchlude them from minificated version? Why we can't revert that megre request when real usecases will appear?

**Comment by jridgewell** [comment]
> Why we can't revert that megre request when real usecases will appear?

We won't remember, the de-opt path (`default`) will catch the methods using 2 and 4 parameters.

**Pull request closed without merging**
