### PR TITLE
Setup DOM for every view test

### PR DESCRIPTION
**Pull request by jridgewell**
Karma QUnit v0.1.5 now removes and reinserts the `#qunit-fixture` element before every test.

Ping https://github.com/karma-runner/karma-qunit/issues/28 and https://github.com/jashkenas/backbone/pull/3742.

### CODE REVIEW

**Comment by paulfalgout** [comment]
Nice!  LGTM.

**Comment by megawac** [comment]
Want to bump `package.json` dev dep version?

**Comment by jridgewell** [comment]
Updated dependencies.

**Comment by akre54** [comment]
Any clue why this is needed? Bit of an ugly hack.

**Comment by megawac** [comment]
So the `index.html` works (this stuff has always been around)

**Comment by akre54** [comment]
No I meant, why do we need to reinsert the testElement every time? It's worked fine up til this point.

**Comment by paulfalgout** [comment]
@akre54 Unfortunately the newest version of karma-qunit recreated the fixture at the start of each test. https://github.com/karma-runner/karma-qunit/pull/22

**Pull request merged**
