### PR TITLE
Fixed a broken link.

### PR DESCRIPTION
**Pull request by ohbarye**
I found a broken link in [the document](http://backbonejs.org/docs/todos.html#section-1), so that fixed it. :)

### CODE REVIEW

**Comment by jridgewell** [comment]
Good eye!

**Comment by akre54** [comment]
Previously: #3545 #1720

These docs are autogenerated by docco, so we shouldn't be editing them by hand.

I looked into this a while back when it last popped up and here's what I remember. The [canonical filename is `localStorage`](https://github.com/jashkenas/backbone/blob/1.2.1/examples/backbone.localStorage.js) (camelCased), but I think I recall at one point it might've been all lowercase (#2204 maybe?), which on case-insensitive filesystems (like OSX's default HFS+) reads in the file file, but spits out the wrong error. Weird. This definitely shouldn't still be happening.

**Comment by ohbarye** [comment]
I'm sorry that I wasn’t aware that. I'll be careful.

**Comment by akre54** [comment]
no harm no foul. thanks for catching it :)

**Pull request merged**
