### PR TITLE
Use strictEqual in Collection#has Tests

### PR DESCRIPTION
**Pull request by jridgewell**
I'm getting failures when testing locally that `assert.notOk` isn't a function. :cry:

Testing the boolean return values is probably intended anyways.

### CODE REVIEW

**Comment by jdalton** [comment]
`notOk` exists in at least QUnit v1.18.0.

http://api.qunitjs.com/notOk/.

**Comment by jridgewell** [comment]
It's a fresh install... Let me try removing `node_modules` and reinstalling.

**Comment by jridgewell** [comment]
The issue is we're serving a vendored QUnit when testing in a browser locally (the `test/index.html` page). Upgrading it to match our npm version fixes it.

**Comment by jdalton** [comment]
Just use the npm one rewire the paths to `node_modules/qunit/qunit.js` or smth.

**Pull request merged**
