### PR TITLE
Backbone Conf videos

### PR DESCRIPTION
**Pull request by brock**
Adds a section called "Talks". I looked at creating a table with tags, but there were so many good talks, and I guess I didn't feel qualified to eliminate any of them. :grinning:

### CODE REVIEW

**Comment by jashkenas** [comment]
I think that a curated table/list with titles and tags would be more valuable then just leaving readers to go wander through on their own ... In particular, it could be a nice complement to the FAQ. Anyone else want to pitch in on this?

**Comment by jmeas** [comment]
I think that it should be a section of the website. Videos are a great reference for developers of all skill levels.

**Comment by jashkenas** [comment]
This is still open for anyone who feels like writing a little bit of HTML.

**Comment by jashkenas** [comment]
Looks like nobody picked this up ... closing.

**Comment by elgubenis** [comment]
I'm late but i'd pick that up, if thats ok

**Comment by jridgewell** [comment]
Sure, mind opening another PR? Bonus points for including @brock's original commit.

**Pull request closed without merging**
