### PR TITLE
Draft changelog for Backbone 1.2.0

### PR DESCRIPTION
**Pull request by akre54**
Still needs:
- [x] document #3039 
- [x] bump Underscore version if #3307 is merged
- [x] update copyright year in LICENSE

### CODE REVIEW

**Comment by akre54** [comment]
@jashkenas where are we at with this?

**Comment by jashkenas** [comment]
I dunno about the status of this particular ticket, but it would be lovely to push out a new release.

**Comment by akre54** [comment]
Yeah I don't particularly care if you use this change log or roll your own
but I think it's time.

**Comment by jashkenas** [comment]
It's long, long past time, my friend.

**Comment by akre54** [comment]
So what's the game plan?

**Comment by megawac** [comment]
Can we make a list of issues to close pre-1.2

**Comment by jashkenas** [comment]
There's only one game plan: Do it.

But I'm afraid I don't have time this afternoon...

**Comment by akre54** [comment]
Nah for sure. I just don't want this to fall off the radar like it has for
the past 8 months.

Happy to help triage some issues and fixup the changelog if it means we're
actually going to launch something.

**Comment by jashkenas** [comment]
Absolutely, and it's appreciated. If you want to whip things into shape — then simply going through and reviewing the open tickets, and the draft changelog, and the edits to the documentation ... is the bulk of it. If you do that, and send me a note that says — hey Jeremy, I reviewed the current status of master, and I'm telling you that it's ready to cut for release — I can give it a glance-over and push one out on your good word ;)

**Comment by akre54** [comment]
Alright @megawac, let's do this :)

Probably not today or tomorrow but I'll take a look Sunday or Monday. Last
I checked there wasn't a ton added since August (
https://github.com/jashkenas/backbone/compare/1.1.2...master)

**Comment by megawac** [comment]
It might be worthwhile to prune a couple of the major dependents before you publish

- [ ] Marionette: 2 router tests are failing (otherwise looks fine)
- [x] Epoxy pass
- [x] Relational pass
- [ ] Associations crash
- [ ] VirtualCollection fails
      - previousAttributes regression?

ETC.

**Comment by EnzoMartin** [comment]
There's a bunch of open PRs that I'd personally love to see make it in for a new release (last one was a year ago)

**Comment by akre54** [comment]
@EnzoMartin any in particular?

**Comment by EnzoMartin** [comment]
@akre54 

Actually a bunch of them got merged recently, woot

There's still #3395 and some "Quality of Life" stuff for the documentation: #3338 #3419

**Comment by akre54** [comment]
@EnzoMartin merged the first two. I'll let Jeremy decide on the last one though I don't see why not (and it also shouldn't block this release regardless)

**Comment by jridgewell** [comment]
Need:
--------

- [ ] https://github.com/jashkenas/backbone/pull/3489
- [ ] https://github.com/jashkenas/backbone/pull/3434 OR https://github.com/jashkenas/backbone/pull/3506
- [ ] https://github.com/jashkenas/backbone/pull/3330

Possibly:
-----------

- [ ] https://github.com/jashkenas/backbone/pull/3421

**Comment by EnzoMartin** [comment]
Any ideas on target release date?

**Comment by akre54** [comment]
I'd like to see us figure out the deal with #3421, #3038 et al before release, but otherwise I think we're good to go. @jridgewell @megawac anything else from you guys?

**Comment by megawac** [comment]
Hmm, just want to run the test suites of dependents on the new version - did anyone ever look into the `VirtualCollection` issue I mentioned

**Comment by akre54** [comment]
No but maybe @p3drosola could chime in. What's busted specifically?

**Comment by jashkenas** [comment]
There you go — I closed those two tickets.

**Comment by p3drosola** [comment]
Hey @megawac @akre54, I just got the mention. Happy to take a look at it. Gimme a minute.

**Comment by megawac** [comment]
What about #3528

**Comment by p3drosola** [comment]
VirtualCollection is now passing properly. thanks for the heads up :tophat:

**Comment by megawac** [comment]
Thanks @p3drosola I think this is almost good to go

**Comment by jridgewell** [comment]
One lass **need**: https://github.com/jashkenas/backbone/pull/3529

**Comment by akre54** [comment]
@jashkenas can we get a resolution on
- [ ] #3553 - use `_.create` in `extend` 
- [ ] #3528 - use global jQuery when available
- [ ] #3207/#3243 - binary search for adding models to Collection
- [ ] #2816 - add `set` event to Collection
- [ ] #3397 / #3396 - late-binding event handlers from string names
- [ ] #3476 - implement events as a linked list
- [ ] #3512 - API change: `remove` returns the list of removed models
- [ ] #3135 - add `Model#when`

**Comment by joshbambrick** [comment]
Updated #3207 in order to use a local version of `comparator`, so wouldn't need to wait for underscore.js update (could implement a patch in future if that method becomes available). Could consider renaming to `binarySearch` or `sortedIndex`, but that is probably not a huge issue.

**Comment by jridgewell** [comment]
Ping @akre54: Mind including #3577 in the notes as well?

**Comment by akre54** [comment]
Will do once it gets merged. In the meantime want to open a pull against my
fork with the changelog addition?

**Comment by akre54** [comment]
We haven't had any major activity in weeks, I think this is good to go. @jashkenas

**Comment by jashkenas** [comment]
Cool. Today's the day then.

**Comment by jridgewell** [comment]
Can we merge #3577 in as well?

**Comment by akre54** [comment]
Hallelujah!

**Pull request merged**
