### PR TITLE
Fixed copyright range to be updated to 2015

### PR DESCRIPTION
**Pull request by arianf**
Updated the copyright from `2014` to be `2015`.

### CODE REVIEW

**Comment by thejameskyle** [comment]
Time to play

merge-or-no-merge

https://github.com/jashkenas/backbone/pull/3452 https://github.com/jashkenas/backbone/pull/3437 https://github.com/jashkenas/backbone/pull/3436

**Comment by samccone** [comment]
nah @thejameskyle I prefer
screen shot 2015-02-08 at 6 43 05 pm

**Comment by samccone** [comment]
Looks like it was partially fixed here https://github.com/jashkenas/backbone/commit/94922c7c424b85aaa9664283abb74283ca3f4a67

**Comment by akre54** [comment]
ts-w4-5p_18x24

**Comment by akre54** [comment]
Uncle. I'll merge if for no reason to stop all these PRs.

**Pull request merged**
