### PR TITLE
Document delegate/undelegate

### PR DESCRIPTION
**Pull request by akre54**
Addresses #3622.

### CODE REVIEW

**Comment by philfreo** [comment]
Should `delegate` and `undelegate` appear in the documentation's left-nav as separate entries? I read in the changelog these methods were added but it was strange to not see them in the left nav under View.

**Comment by akre54** [comment]
They're not really meant to get called by your average user, they're mostly just there to give plugin authors a consistent way of handling event binding. A one-paragraph note seems like it's consistent with the rest of the docs. Any reason we'd need to call them out specifically?

**Comment by philfreo** [comment]
I just wasn't aware of any other methods that weren't "private" but that weren't documented, so it just seemed inconsistent

**Comment by akre54** [comment]
Routing and history are the big ones, but there's also the bits about `render` and `template` and the events hash in `delegateEvents`. `delegate` and `undelegate` are kind of unique in Backbone: most "private" methods are prefixed with an underscore to show they're unstable implementation details. These are stable -- they're not going to change anytime soon.

I don't feel strongly though -- it just feels like added clutter.

**Pull request merged**
