### PR TITLE
Fix the collection.prototype.modelId method to don't crash when the model property is undefined

### PR DESCRIPTION
**Pull request by gartz**
Create generic collections where has no model property defined, should not crash on the method `modelId`, it just should search for the default `idAttribute`, and keep working.

Tests included.

### CODE REVIEW

**Comment by akre54** [comment]
Sorry -- what's the use case for this? You almost always want `model` to be defined. If you're doing something funky, just override `modelId` yourself.

**Comment by gartz** [comment]
Old versions this doesn't broken, so it's breaking on Backbone updating. For huge project just if we patch the backbone lib all the time, that is bad.

**Comment by akre54** [comment]
To quote [from the docs](http://backbonejs.org/#FAQ-extending):
> Many JavaScript libraries are meant to be insular and self-enclosed, where you interact with them by calling their public API, but never peek inside at the guts. Backbone.js is not that kind of library. ... If you catch yourself adding methods to Backbone.Model.prototype, or creating your own base subclass, don't worry — that's how things are supposed to work.

It's a good idea to have your own "base" model and collection classes just for this reason. It becomes a simple and straightforward change once you do.

**Comment by jashkenas** [comment]
Isn't a `model` property defined by default?

**Comment by gartz** [comment]
it should, but if `model` is required by a collection and must be a `Model` constructor, it should be test and throw a error that drive the developer to the source of the problem.
This bug just happens because a requirement wasn't filled and there isn't a check of feedback for the requirement. 

I agree with the quote from @akre54  and I still think this shouldn't generate the current exception in the `modelId` method.

**Comment by akre54** [comment]
But it works correctly out of the box. If *you* do something nonstandard like override model to be `undefined` in your app then it shouldn't be a surprise that this breaks some things. `modelId` is exposed specifically to allow you to override it in cases like this.

**Pull request closed without merging**
