### PR TITLE
model.fetch.then

### PR DESCRIPTION
**Pull request by godlark**
Recently I've made code similiar to:

book.fetch().then(function(resp) {
});

And I've expected to get a parsed response with my 'Book.parse' function but I've got a raw response.

### CODE REVIEW

**Comment by akre54** [comment]
Closing in favor of #3729 and #3651. Please do a search before opening issues.

**Comment by godlark** [comment]
Have you read the issue before closing? My pull request complain about how fetch function works. I DO NOT complain about using jquery.Deffered etc.

**Comment by akre54** [comment]
`Backbone.sync` [proxies to `Backbone.ajax`](https://github.com/jashkenas/backbone/blob/1.2.2/backbone.js#L1410) behind the scenes. The `then` function you're getting from the return value of `fetch` is simply the return value from jQuery.ajax, a `jqxhr` (xhr wrapped in jQuery.Deferred.)

Backbone has no use for Promises at the moment. We don't even guarantee that the fetch function will return a `thenable` (i.e. a function with a `then` method) as your change requires, therefore we can't add add this change until we make some major plumbing decisions like the ones in #3729 and #3651. If you want this change, stop by those issues and register your input, they might have already added it.

**Comment by godlark** [comment]
Ok, thanks for the reply :)

**Pull request closed without merging**
